<?php exit;?> [Notice] : Array to string conversion in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 332
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 170
<?php exit;?> [Notice] : Array to string conversion in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 332
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 338
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 170
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 338
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 338
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 338
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 170
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 338
<?php exit;?> [Warning] : Cannot modify header information - headers already sent by (output started at D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php:8) in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 170
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  3 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 336
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Notice] : Undefined offset:  4 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 335
<?php exit;?> [Warning] : base_model::include(D:/AppServ/www/xn/framework2.0/test/model/set_cacheconf.class.php) [<a href='base-model.include'>base-model.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 100
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Notice] : Undefined offset:  1 in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 250
<?php exit;?> [Notice] : Undefined offset:  2 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 339
<?php exit;?> [Notice] : Undefined offset:  2 in File D:\AppServ\www\xn\framework2.0\lib\db_mysql.class.php, Line: 339
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Warning] : core::include(D:/AppServ/www/xn/framework2.0/test/model/Memcache.class.php) [<a href='core.include'>core.include</a>]: failed to open stream: No such file or directory in File D:\AppServ\www\xn\framework2.0\lib\core.class.php, Line: 154
<?php exit;?> [Notice] : Undefined variable: r1 in File D:\AppServ\www\xn\framework2.0\test\test_base_model.php, Line: 39
<?php exit;?> [Notice] : Undefined variable: dbinstance in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 121
<?php exit;?> [Warning] : Missing argument 1 for base_model::get_dbinstance(), called in D:\AppServ\www\xn\framework2.0\lib\base_model.class.php on line 73 and defined in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 99
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  host in File D:\AppServ\www\xn\framework2.0\lib\base_model.class.php, Line: 102
<?php exit;?> [Notice] : Undefined index:  mysql in File D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php, Line: 21
<?php exit;?> [Notice] : Undefined index:  mysql in File D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php, Line: 21
<?php exit;?> [Notice] : Undefined variable: a in File D:\AppServ\www\xn\framework2.0\test\test_db_mysql.php, Line: 23
<?php exit;?>	12-7-19 05:57	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:11	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Notice] : Undefined variable: a in File D:\www\xxx.net\framework2.3\test\test_db_mongodb.php, Line: 20 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:11	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Notice] : Undefined variable: a in File D:\www\xxx.net\framework2.3\test\test_db_mongodb.php, Line: 20 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:11	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Notice] : Undefined variable: a in File D:\www\xxx.net\framework2.3\test\test_db_mongodb.php, Line: 20 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:11	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Notice] : Undefined variable: a in File D:\www\xxx.net\framework2.3\test\test_db_mongodb.php, Line: 20 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:12	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:13	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:13	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:13	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:14	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:14	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:14	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:14	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:14	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:14	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:33	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:35	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:35	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:35	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:35	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:35	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:36		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	Mongo Extension not loaded. File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [28]	
<?php exit;?>	12-7-19 06:36		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Notice] : ob_end_clean() [<a href='ref.outcontrol'>ref.outcontrol</a>]: failed to delete buffer. No buffer to delete. in File D:\www\xxx.net\framework2.3\lib\xn_exception.class.php, Line: 120	
<?php exit;?>	12-7-19 06:36	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:36	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:36	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:36	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:36	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:36	127.0.0.1	/framework2.3/test/test_db_mongodb.php	[Warning] : Invalid argument supplied for foreach() in File D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php, Line: 220 File: D:\www\xxx.net\framework2.3\lib\core.class.php [203]	
<?php exit;?>	12-7-19 06:38	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:38	127.0.0.1	/framework2.3/test/test_db_mongodb.php	不能连接到 Mongodb 服务器，Error:Unknown error File: D:\www\xxx.net\framework2.3\lib\db_mongodb.class.php [253]	
<?php exit;?>	12-7-19 06:42	127.0.0.1	/framework2.3/test/test_db_mysql.php	MySQL Query Error:SELECT MAX(uid) FROM bbs_fuser. Table 'rc2.bbs_fuser' doesn't exist File: D:\www\xxx.net\framework2.3\lib\db_mysql.class.php [305]	
<?php exit;?>	12-7-19 06:42	127.0.0.1	/framework2.3/test/test_db_mysql.php	MySQL Query Error:SELECT MAX(uid) FROM bbs_fuser. Table 'rc2.bbs_fuser' doesn't exist File: D:\www\xxx.net\framework2.3\lib\db_mysql.class.php [305]	
<?php exit;?>	12-7-19 06:43	127.0.0.1	/framework2.3/test/test_db_mysql.php	MySQL Query Error:SELECT MAX(uid) FROM bbs_fuser. Table 'rc2.bbs_fuser' doesn't exist File: D:\www\xxx.net\framework2.3\lib\db_mysql.class.php [305]	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Notice] : Undefined index:  memcached in File D:\www\xxx.net\framework2.4\test\test_cache_memcache.php, Line: 18 File: D:\www\xxx.net\framework2.4\core\core.class.php [258]	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 92	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 93	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 92	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 93	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 92	
<?php exit;?>	12-12-4 02:38		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 93	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	Memcache Extension not loaded. File: D:\www\xxx.net\framework2.4\cache\cache_memcache.class.php [36]	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 92	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 93	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 92	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 93	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 92	
<?php exit;?>	12-12-4 02:39		?start_debug=1&debug_port=10001&debug_fastfile=1&debug_host=127.0.0.1	[Warning] : Cannot modify header information - headers already sent by (output started at D:\www\xxx.net\framework2.4\test\test_cache_memcache.php:8) in File D:\www\xxx.net\framework2.4\core\core.class.php, Line: 93	
<?php exit;?>	13-2-15 14:47	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:47	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:48	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:49	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:52	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:53	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 636 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:53	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 627 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:55	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:8) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [293]	
<?php exit;?>	13-2-15 14:55	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [293]	
<?php exit;?>	13-2-15 14:56	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 637 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [293]	
<?php exit;?>	13-2-15 14:56	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 639 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [295]	
<?php exit;?>	13-2-15 14:56	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 638 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:57	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 638 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:57	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 638 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [294]	
<?php exit;?>	13-2-15 14:58	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 634 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [293]	
<?php exit;?>	13-2-15 14:59	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 638 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [293]	
<?php exit;?>	13-2-15 14:59	127.0.0.1	/framework2.4/test/test_db_mongodb.php	[Warning] : Cannot modify header information - headers already sent by (output started at E:\www\xiuno.2.0.0\framework2.4\test\test_db_mongodb.php:10) in File E:\www\xiuno.2.0.0\framework2.4\core\core.class.php, Line: 638 File: E:\www\xiuno.2.0.0\framework2.4\core\core.class.php [293]	
<?php exit;?>	13-2-15 15:01	127.0.0.1	/framework2.4/test/test_db_mongodb.php	Mongo Extension not loaded. File: E:\www\xiuno.2.0.0\framework2.4\db\db_mongodb.class.php [30]	
